// ========================================
// FAMILY TREE DATA - Enhanced with Canvas Positions
// ========================================

let members = [
  { id: 1, pid: 'PID001', tid: 'W01', name: 'Patekai', firstName: 'Patekai', lastName: '', sex: 'M', birth: '01/01/1800', death: '12/15/1875', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: 'Royal Compound', phone: '', email: '', parentPids: [], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'Yes', canvasX: 1000, canvasY: 100 },
  { id: 2, pid: 'PID002', tid: 'W01', name: 'Endao', firstName: 'Endao', lastName: '', sex: 'F', birth: '03/12/1805', death: '05/20/1860', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: 'Royal Compound', phone: '', email: '', parentPids: [], spousePid: 'PID001', marriageDate: '01/10/1820', divorceDate: '', photo: '', spouseStatus: 'Yes', canvasX: 800, canvasY: 300 },
  { id: 3, pid: 'PID007', tid: 'W01-SD01', name: 'Unggas', firstName: 'Unggas', lastName: '', sex: 'M', birth: '02/14/1825', death: '07/10/1890', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 700, canvasY: 500 },
  { id: 4, pid: 'PID008', tid: 'W01-SD02', name: 'Gino', firstName: 'Gino', lastName: '', sex: 'M', birth: '04/18/1827', death: '09/15/1895', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 850, canvasY: 500 },
  { id: 5, pid: 'PID009', tid: 'W01-SD03', name: 'Anas', firstName: 'Anas', lastName: '', sex: 'M', birth: '06/22/1830', death: '11/05/1900', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1000, canvasY: 500 },
  { id: 6, pid: 'PID010', tid: 'W01-SD04', name: 'Jama', firstName: 'Jama', lastName: '', sex: 'F', birth: '08/30/1833', death: '02/14/1885', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1150, canvasY: 500 },
  { id: 7, pid: 'PID011', tid: 'W01-SD05', name: 'Dangalan', firstName: 'Dangalan', lastName: '', sex: 'M', birth: '10/05/1836', death: '04/22/1910', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1300, canvasY: 500 },
  { id: 8, pid: 'PID012', tid: 'W01-SD06', name: 'Kanda', firstName: 'Kanda', lastName: '', sex: 'F', birth: '12/12/1839', death: '06/30/1898', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 550, canvasY: 500 },
  { id: 9, pid: 'PID013', tid: 'W01-SD07', name: 'Kusa', firstName: 'Kusa', lastName: '', sex: 'M', birth: '01/25/1842', death: '08/17/1915', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID002'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 400, canvasY: 500 },
  { id: 10, pid: 'PID003', tid: 'W02', name: 'Empek', firstName: 'Empek', lastName: '', sex: 'F', birth: '05/05/1810', death: '03/12/1870', country: 'Philippines', region: 'BARMM', city: 'Sultan Kudarat', address: 'Royal Compound', phone: '', email: '', parentPids: [], spousePid: 'PID001', marriageDate: '06/15/1840', divorceDate: '', photo: '', spouseStatus: 'Yes', canvasX: 1200, canvasY: 300 },
  { id: 11, pid: 'PID014', tid: 'W02-SD01', name: 'Unos', firstName: 'Unos', lastName: '', sex: 'M', birth: '07/20/1842', death: '10/10/1905', country: 'Philippines', region: 'BARMM', city: 'Sultan Kudarat', address: '', parentPids: ['PID001', 'PID003'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1450, canvasY: 500 },
  { id: 12, pid: 'PID015', tid: 'W02-SD02', name: 'Daynko', firstName: 'Daynko', lastName: '', sex: 'F', birth: '09/25/1845', death: '12/05/1900', country: 'Philippines', region: 'BARMM', city: 'Sultan Kudarat', address: '', parentPids: ['PID001', 'PID003'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1600, canvasY: 500 },
  { id: 13, pid: 'PID016', tid: 'W02-SD03', name: 'Dagedeban', firstName: 'Dagedeban', lastName: '', sex: 'M', birth: '11/30/1848', death: '01/15/1912', country: 'Philippines', region: 'BARMM', city: 'Sultan Kudarat', address: '', parentPids: ['PID001', 'PID003'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1750, canvasY: 500 },
  { id: 14, pid: 'PID017', tid: 'W02-SD04', name: 'Kiram', firstName: 'Kiram', lastName: '', sex: 'M', birth: '02/14/1852', death: '05/20/1918', country: 'Philippines', region: 'BARMM', city: 'Sultan Kudarat', address: '', parentPids: ['PID001', 'PID003'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1900, canvasY: 500 },
  { id: 15, pid: 'PID004', tid: 'W03', name: 'Amina', firstName: 'Amina', lastName: '', sex: 'F', birth: '08/10/1815', death: '07/25/1880', country: 'Philippines', region: 'BARMM', city: 'Marawi', address: 'Royal Compound', phone: '', email: '', parentPids: [], spousePid: 'PID001', marriageDate: '04/20/1855', divorceDate: '', photo: '', spouseStatus: 'Yes', canvasX: 600, canvasY: 300 },
  { id: 16, pid: 'PID018', tid: 'W03-SD01', name: 'Pamogon', firstName: 'Pamogon', lastName: '', sex: 'M', birth: '06/18/1857', death: '09/30/1925', country: 'Philippines', region: 'BARMM', city: 'Marawi', address: '', parentPids: ['PID001', 'PID004'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 250, canvasY: 500 },
  { id: 17, pid: 'PID019', tid: 'W03-SD02', name: 'Paga', firstName: 'Paga', lastName: '', sex: 'F', birth: '08/22/1860', death: '11/12/1920', country: 'Philippines', region: 'BARMM', city: 'Marawi', address: '', parentPids: ['PID001', 'PID004'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 100, canvasY: 500 },
  { id: 18, pid: 'PID020', tid: 'W03-SD03', name: 'Bulos', firstName: 'Bulos', lastName: '', sex: 'M', birth: '10/05/1863', death: '02/18/1930', country: 'Philippines', region: 'BARMM', city: 'Marawi', address: '', parentPids: ['PID001', 'PID004'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 2050, canvasY: 500 },
  { id: 19, pid: 'PID021', tid: 'W03-SD04', name: 'Tingalong', firstName: 'Tingalong', lastName: '', sex: 'F', birth: '12/10/1866', death: '04/25/1928', country: 'Philippines', region: 'BARMM', city: 'Marawi', address: '', parentPids: ['PID001', 'PID004'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 2200, canvasY: 500 },
  { id: 20, pid: 'PID022', tid: 'W03-SD05', name: 'Sanduyogan', firstName: 'Sanduyogan', lastName: '', sex: 'M', birth: '01/15/1870', death: '03/20/1940', country: 'Philippines', region: 'BARMM', city: 'Marawi', address: '', parentPids: ['PID001', 'PID004'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 2350, canvasY: 500 },
  { id: 21, pid: 'PID005', tid: 'W04', name: '[Name Unknown]', firstName: '[Name Unknown]', lastName: '', sex: 'F', birth: '', death: '', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: 'Royal Compound', phone: '', email: '', parentPids: [], spousePid: 'PID001', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1400, canvasY: 300 },
  { id: 22, pid: 'PID006', tid: 'W05', name: 'Elmas', firstName: 'Elmas', lastName: '', sex: 'F', birth: '07/10/1820', death: '10/15/1885', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: 'Royal Compound', phone: '', email: '', parentPids: [], spousePid: 'PID001', marriageDate: '05/10/1860', divorceDate: '', photo: '', spouseStatus: 'Yes', canvasX: 400, canvasY: 300 },
  { id: 23, pid: 'PID023', tid: 'W05-SD01', name: 'Bagal', firstName: 'Bagal', lastName: '', sex: 'M', birth: '08/20/1862', death: '12/10/1935', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID006'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 2500, canvasY: 500 },
  { id: 24, pid: 'PID024', tid: 'W05-SD02', name: 'Tumog', firstName: 'Tumog', lastName: '', sex: 'F', birth: '03/12/1865', death: '07/18/1940', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID001', 'PID006'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 2650, canvasY: 500 },
  // Unggas's Children
  { id: 25, pid: 'PID025', tid: 'W01-SD01-GSD01', name: 'Sindatok', firstName: 'Sindatok', lastName: '', sex: 'M', birth: '01/01/1845', death: '', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID007'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'Unknown', canvasX: 600, canvasY: 700 },
  { id: 26, pid: 'PID026', tid: 'W01-SD01-GSD02', name: 'Angga', firstName: 'Angga', lastName: '', sex: 'M', birth: '03/15/1847', death: '', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID007'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 750, canvasY: 700 },
  { id: 27, pid: 'PID027', tid: 'W01-SD01-GSD03', name: 'Gayong', firstName: 'Gayong', lastName: '', sex: 'F', birth: '06/20/1849', death: '', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID007'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 900, canvasY: 700 },
  { id: 28, pid: 'PID028', tid: 'W01-SD01-GSD04', name: 'Pananggilan', firstName: 'Pananggilan', lastName: '', sex: 'M', birth: '09/10/1851', death: '', country: 'Philippines', region: 'BARMM', city: 'Cotabato City', address: '', parentPids: ['PID007'], spousePid: '', marriageDate: '', divorceDate: '', photo: '', spouseStatus: 'No', canvasX: 1050, canvasY: 700 }
];

// Philippine city data
const philippineCities = {
  'BARMM': ['Cotabato City', 'Sultan Kudarat', 'Marawi'],
  'NCR': ['Manila', 'Quezon City', 'Makati']
};
